//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Form1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FullOrderInfo
    {
        public int IdOrder { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public string DefectDescription { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string ServiceNames { get; set; }
        public Nullable<int> IdPart { get; set; }
        public string PartName { get; set; }
    }
}
